services:
  - type: web
    name: ecommerce-app
    runtime: docker
    plan: free
    region: oregon
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/ecommerce-app-1.0.0.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
